# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QTabWidget,
    QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1909, 1310)
        self.menu02_Sub01_DataFolderSelect = QAction(MainWindow)
        self.menu02_Sub01_DataFolderSelect.setObjectName(u"menu02_Sub01_DataFolderSelect")
        self.menu02_Sub02_Data2 = QAction(MainWindow)
        self.menu02_Sub02_Data2.setObjectName(u"menu02_Sub02_Data2")
        self.menu02_Sub03_Data3 = QAction(MainWindow)
        self.menu02_Sub03_Data3.setObjectName(u"menu02_Sub03_Data3")
        self.menu02_Sub04_Data4 = QAction(MainWindow)
        self.menu02_Sub04_Data4.setObjectName(u"menu02_Sub04_Data4")
        self.actionDataSub01_01 = QAction(MainWindow)
        self.actionDataSub01_01.setObjectName(u"actionDataSub01_01")
        self.actionDataSub01_02 = QAction(MainWindow)
        self.actionDataSub01_02.setObjectName(u"actionDataSub01_02")
        self.actionDataSub01_03 = QAction(MainWindow)
        self.actionDataSub01_03.setObjectName(u"actionDataSub01_03")
        self.actionDataSub01_04 = QAction(MainWindow)
        self.actionDataSub01_04.setObjectName(u"actionDataSub01_04")
        self.actionDataSub01_05 = QAction(MainWindow)
        self.actionDataSub01_05.setObjectName(u"actionDataSub01_05")
        self.actionbdo = QAction(MainWindow)
        self.actionbdo.setObjectName(u"actionbdo")
        self.actionbodong = QAction(MainWindow)
        self.actionbodong.setObjectName(u"actionbodong")
        self.actionma = QAction(MainWindow)
        self.actionma.setObjectName(u"actionma")
        self.actionregression = QAction(MainWindow)
        self.actionregression.setObjectName(u"actionregression")
        self.actiontimeseq = QAction(MainWindow)
        self.actiontimeseq.setObjectName(u"actiontimeseq")
        self.actiongarch = QAction(MainWindow)
        self.actiongarch.setObjectName(u"actiongarch")
        self.actionpca = QAction(MainWindow)
        self.actionpca.setObjectName(u"actionpca")
        self.actionbaiys = QAction(MainWindow)
        self.actionbaiys.setObjectName(u"actionbaiys")
        self.actionfft = QAction(MainWindow)
        self.actionfft.setObjectName(u"actionfft")
        self.actionarima = QAction(MainWindow)
        self.actionarima.setObjectName(u"actionarima")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget_mainWindow = QTabWidget(self.centralwidget)
        self.tabWidget_mainWindow.setObjectName(u"tabWidget_mainWindow")
        self.tabWidget_mainWindow.setGeometry(QRect(20, 10, 1841, 1221))
        font = QFont()
        font.setFamilies([u"\u6977\u4f53"])
        font.setPointSize(14)
        font.setBold(False)
        self.tabWidget_mainWindow.setFont(font)
        self.tabWidget_mainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tabWidget_mainWindow.setIconSize(QSize(16, 16))
        self.tabWidget_mainWindow.setElideMode(Qt.TextElideMode.ElideMiddle)
        self.tab01_DataSetting = QWidget()
        self.tab01_DataSetting.setObjectName(u"tab01_DataSetting")
        self.GroupBox01_DataSource = QGroupBox(self.tab01_DataSetting)
        self.GroupBox01_DataSource.setObjectName(u"GroupBox01_DataSource")
        self.GroupBox01_DataSource.setGeometry(QRect(60, 10, 1741, 331))
        self.GroupBox01_DataSource.setBaseSize(QSize(0, 3))
        self.lab_Specify_API_list_Name = QLabel(self.GroupBox01_DataSource)
        self.lab_Specify_API_list_Name.setObjectName(u"lab_Specify_API_list_Name")
        self.lab_Specify_API_list_Name.setGeometry(QRect(40, 100, 291, 16))
        self.txt_Specify_API_list_Name = QPlainTextEdit(self.GroupBox01_DataSource)
        self.txt_Specify_API_list_Name.setObjectName(u"txt_Specify_API_list_Name")
        self.txt_Specify_API_list_Name.setGeometry(QRect(340, 90, 441, 31))
        self.txt_Specify_API_log_Name = QPlainTextEdit(self.GroupBox01_DataSource)
        self.txt_Specify_API_log_Name.setObjectName(u"txt_Specify_API_log_Name")
        self.txt_Specify_API_log_Name.setGeometry(QRect(340, 130, 441, 31))
        self.lab_Specify_API_log_Name = QLabel(self.GroupBox01_DataSource)
        self.lab_Specify_API_log_Name.setObjectName(u"lab_Specify_API_log_Name")
        self.lab_Specify_API_log_Name.setGeometry(QRect(40, 140, 291, 16))
        self.lab_Specify_Initial_Path = QLabel(self.GroupBox01_DataSource)
        self.lab_Specify_Initial_Path.setObjectName(u"lab_Specify_Initial_Path")
        self.lab_Specify_Initial_Path.setGeometry(QRect(40, 180, 291, 16))
        self.txt_Specify_Initial_Path = QPlainTextEdit(self.GroupBox01_DataSource)
        self.txt_Specify_Initial_Path.setObjectName(u"txt_Specify_Initial_Path")
        self.txt_Specify_Initial_Path.setGeometry(QRect(340, 170, 1011, 31))
        font1 = QFont()
        font1.setFamilies([u"\u6977\u4f53"])
        font1.setPointSize(10)
        font1.setBold(False)
        self.txt_Specify_Initial_Path.setFont(font1)
        self.pushBttn_API_InitialPath = QPushButton(self.GroupBox01_DataSource)
        self.pushBttn_API_InitialPath.setObjectName(u"pushBttn_API_InitialPath")
        self.pushBttn_API_InitialPath.setGeometry(QRect(1390, 160, 261, 41))
        self.pushBttn_API_InitialPath.setMouseTracking(True)
        self.radioBttn04_Other = QRadioButton(self.GroupBox01_DataSource)
        self.radioBttn04_Other.setObjectName(u"radioBttn04_Other")
        self.radioBttn04_Other.setGeometry(QRect(860, 50, 96, 20))
        self.radioBttn03_Choice = QRadioButton(self.GroupBox01_DataSource)
        self.radioBttn03_Choice.setObjectName(u"radioBttn03_Choice")
        self.radioBttn03_Choice.setGeometry(QRect(580, 50, 161, 20))
        self.radioBttn02_AST = QRadioButton(self.GroupBox01_DataSource)
        self.radioBttn02_AST.setObjectName(u"radioBttn02_AST")
        self.radioBttn02_AST.setGeometry(QRect(290, 50, 96, 20))
        self.radioBttn01_TuShare = QRadioButton(self.GroupBox01_DataSource)
        self.radioBttn01_TuShare.setObjectName(u"radioBttn01_TuShare")
        self.radioBttn01_TuShare.setGeometry(QRect(40, 50, 161, 20))
        self.pushBttn_API_GeneratList = QPushButton(self.GroupBox01_DataSource)
        self.pushBttn_API_GeneratList.setObjectName(u"pushBttn_API_GeneratList")
        self.pushBttn_API_GeneratList.setGeometry(QRect(1390, 220, 261, 41))
        self.txt_logger = QPlainTextEdit(self.GroupBox01_DataSource)
        self.txt_logger.setObjectName(u"txt_logger")
        self.txt_logger.setGeometry(QRect(130, 210, 1221, 111))
        font2 = QFont()
        font2.setFamilies([u"\u6977\u4f53"])
        font2.setPointSize(12)
        font2.setBold(False)
        self.txt_logger.setFont(font2)
        self.txt_logger.setMouseTracking(True)
        self.txt_logger.setAutoFillBackground(True)
        self.txt_logger.setStyleSheet(u"QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: black;\n"
"}")
        self.txt_logger.setMaximumBlockCount(5)
        self.lab_Terminal = QLabel(self.GroupBox01_DataSource)
        self.lab_Terminal.setObjectName(u"lab_Terminal")
        self.lab_Terminal.setGeometry(QRect(40, 220, 101, 16))
        self.GroupBox02_DataStorage = QGroupBox(self.tab01_DataSetting)
        self.GroupBox02_DataStorage.setObjectName(u"GroupBox02_DataStorage")
        self.GroupBox02_DataStorage.setGeometry(QRect(60, 350, 1081, 401))
        self.radioBttn01_SSMS_SQL = QRadioButton(self.GroupBox02_DataStorage)
        self.radioBttn01_SSMS_SQL.setObjectName(u"radioBttn01_SSMS_SQL")
        self.radioBttn01_SSMS_SQL.setGeometry(QRect(50, 40, 231, 20))
        self.radioBttn02_mySQL = QRadioButton(self.GroupBox02_DataStorage)
        self.radioBttn02_mySQL.setObjectName(u"radioBttn02_mySQL")
        self.radioBttn02_mySQL.setGeometry(QRect(420, 40, 161, 20))
        self.radioBttn03_OtherDB = QRadioButton(self.GroupBox02_DataStorage)
        self.radioBttn03_OtherDB.setObjectName(u"radioBttn03_OtherDB")
        self.radioBttn03_OtherDB.setGeometry(QRect(790, 50, 161, 20))
        self.tabWidgetTab01_DB_Select = QTabWidget(self.GroupBox02_DataStorage)
        self.tabWidgetTab01_DB_Select.setObjectName(u"tabWidgetTab01_DB_Select")
        self.tabWidgetTab01_DB_Select.setGeometry(QRect(40, 90, 1011, 291))
        self.tab01_MS_SQL = QWidget()
        self.tab01_MS_SQL.setObjectName(u"tab01_MS_SQL")
        self.tabWidgetTab01_DB_Select.addTab(self.tab01_MS_SQL, "")
        self.tab02_mySQL = QWidget()
        self.tab02_mySQL.setObjectName(u"tab02_mySQL")
        self.tabWidgetTab01_DB_Select.addTab(self.tab02_mySQL, "")
        self.tab03_OtherDB = QWidget()
        self.tab03_OtherDB.setObjectName(u"tab03_OtherDB")
        self.tabWidgetTab01_DB_Select.addTab(self.tab03_OtherDB, "")
        self.GroupBox03_DataInitilization = QGroupBox(self.tab01_DataSetting)
        self.GroupBox03_DataInitilization.setObjectName(u"GroupBox03_DataInitilization")
        self.GroupBox03_DataInitilization.setGeometry(QRect(60, 760, 1081, 401))
        self.tabWidget_mainWindow.addTab(self.tab01_DataSetting, "")
        self.tab02_DataDownLoad = QWidget()
        self.tab02_DataDownLoad.setObjectName(u"tab02_DataDownLoad")
        self.tabWidget_mainWindow.addTab(self.tab02_DataDownLoad, "")
        self.tab03_AnalysisSetting = QWidget()
        self.tab03_AnalysisSetting.setObjectName(u"tab03_AnalysisSetting")
        self.tabWidget = QTabWidget(self.tab03_AnalysisSetting)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(30, 80, 1761, 1071))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.tabWidget.addTab(self.tab_12, "")
        self.tabWidget_mainWindow.addTab(self.tab03_AnalysisSetting, "")
        self.tab04_AnalysisOutput = QWidget()
        self.tab04_AnalysisOutput.setObjectName(u"tab04_AnalysisOutput")
        self.tabWidget_mainWindow.addTab(self.tab04_AnalysisOutput, "")
        self.tab05_BackTesting = QWidget()
        self.tab05_BackTesting.setObjectName(u"tab05_BackTesting")
        self.tabWidget_mainWindow.addTab(self.tab05_BackTesting, "")
        self.tab06_EffectRank = QWidget()
        self.tab06_EffectRank.setObjectName(u"tab06_EffectRank")
        self.tabWidget_mainWindow.addTab(self.tab06_EffectRank, "")
        self.tab07_VersionControl = QWidget()
        self.tab07_VersionControl.setObjectName(u"tab07_VersionControl")
        self.tabWidget_mainWindow.addTab(self.tab07_VersionControl, "")
        self.tab08_SystemMaintenance = QWidget()
        self.tab08_SystemMaintenance.setObjectName(u"tab08_SystemMaintenance")
        self.tabWidget_mainWindow.addTab(self.tab08_SystemMaintenance, "")
        self.tab09_DevelopDocument = QWidget()
        self.tab09_DevelopDocument.setObjectName(u"tab09_DevelopDocument")
        self.tabWidget_mainWindow.addTab(self.tab09_DevelopDocument, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1909, 30))
        font3 = QFont()
        font3.setPointSize(14)
        self.menubar.setFont(font3)
        self.menu01_File = QMenu(self.menubar)
        self.menu01_File.setObjectName(u"menu01_File")
        self.menu02_Data = QMenu(self.menubar)
        self.menu02_Data.setObjectName(u"menu02_Data")
        self.menu03_AnalysisSetting = QMenu(self.menubar)
        self.menu03_AnalysisSetting.setObjectName(u"menu03_AnalysisSetting")
        self.menu04_AnalysisResult = QMenu(self.menubar)
        self.menu04_AnalysisResult.setObjectName(u"menu04_AnalysisResult")
        self.menu05_BackTesting = QMenu(self.menubar)
        self.menu05_BackTesting.setObjectName(u"menu05_BackTesting")
        self.menu05_BackTesting.setToolTipDuration(-3)
        self.menu06_EffectRank = QMenu(self.menubar)
        self.menu06_EffectRank.setObjectName(u"menu06_EffectRank")
        self.menu07_VersionControl = QMenu(self.menubar)
        self.menu07_VersionControl.setObjectName(u"menu07_VersionControl")
        self.menu08_SystemMaintenance = QMenu(self.menubar)
        self.menu08_SystemMaintenance.setObjectName(u"menu08_SystemMaintenance")
        self.menu09_DevelopmentDocument = QMenu(self.menubar)
        self.menu09_DevelopmentDocument.setObjectName(u"menu09_DevelopmentDocument")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.tabWidget_mainWindow, self.radioBttn01_TuShare)
        QWidget.setTabOrder(self.radioBttn01_TuShare, self.radioBttn02_AST)
        QWidget.setTabOrder(self.radioBttn02_AST, self.pushBttn_API_GeneratList)
        QWidget.setTabOrder(self.pushBttn_API_GeneratList, self.radioBttn03_Choice)
        QWidget.setTabOrder(self.radioBttn03_Choice, self.radioBttn04_Other)
        QWidget.setTabOrder(self.radioBttn04_Other, self.txt_Specify_API_list_Name)
        QWidget.setTabOrder(self.txt_Specify_API_list_Name, self.txt_Specify_API_log_Name)
        QWidget.setTabOrder(self.txt_Specify_API_log_Name, self.txt_Specify_Initial_Path)
        QWidget.setTabOrder(self.txt_Specify_Initial_Path, self.pushBttn_API_InitialPath)
        QWidget.setTabOrder(self.pushBttn_API_InitialPath, self.radioBttn01_SSMS_SQL)
        QWidget.setTabOrder(self.radioBttn01_SSMS_SQL, self.radioBttn02_mySQL)
        QWidget.setTabOrder(self.radioBttn02_mySQL, self.radioBttn03_OtherDB)
        QWidget.setTabOrder(self.radioBttn03_OtherDB, self.tabWidgetTab01_DB_Select)
        QWidget.setTabOrder(self.tabWidgetTab01_DB_Select, self.tabWidget)

        self.menubar.addAction(self.menu01_File.menuAction())
        self.menubar.addAction(self.menu02_Data.menuAction())
        self.menubar.addAction(self.menu03_AnalysisSetting.menuAction())
        self.menubar.addAction(self.menu04_AnalysisResult.menuAction())
        self.menubar.addAction(self.menu05_BackTesting.menuAction())
        self.menubar.addAction(self.menu06_EffectRank.menuAction())
        self.menubar.addAction(self.menu07_VersionControl.menuAction())
        self.menubar.addAction(self.menu08_SystemMaintenance.menuAction())
        self.menubar.addAction(self.menu09_DevelopmentDocument.menuAction())
        self.menu02_Data.addAction(self.menu02_Sub01_DataFolderSelect)
        self.menu02_Data.addAction(self.menu02_Sub02_Data2)
        self.menu02_Data.addAction(self.menu02_Sub03_Data3)
        self.menu02_Data.addSeparator()
        self.menu02_Data.addAction(self.menu02_Sub04_Data4)
        self.menu03_AnalysisSetting.addSeparator()
        self.menu03_AnalysisSetting.addAction(self.actionbodong)
        self.menu03_AnalysisSetting.addAction(self.actionma)
        self.menu03_AnalysisSetting.addAction(self.actionregression)
        self.menu03_AnalysisSetting.addAction(self.actiontimeseq)
        self.menu03_AnalysisSetting.addAction(self.actiongarch)
        self.menu03_AnalysisSetting.addAction(self.actionpca)
        self.menu03_AnalysisSetting.addAction(self.actionbaiys)
        self.menu03_AnalysisSetting.addAction(self.actionfft)
        self.menu03_AnalysisSetting.addAction(self.actionarima)
        self.menu09_DevelopmentDocument.addAction(self.actionbdo)

        self.retranslateUi(MainWindow)

        self.tabWidget_mainWindow.setCurrentIndex(0)
        self.tabWidgetTab01_DB_Select.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u54c8\u54c8\uff0c\u592a\u597d\u73a9\u4e86", None))
        self.menu02_Sub01_DataFolderSelect.setText(QCoreApplication.translate("MainWindow", u"\u6307\u5b9a\u6570\u636e\u6e90", None))
        self.menu02_Sub02_Data2.setText(QCoreApplication.translate("MainWindow", u"Data02", None))
        self.menu02_Sub03_Data3.setText(QCoreApplication.translate("MainWindow", u"Data03", None))
        self.menu02_Sub04_Data4.setText(QCoreApplication.translate("MainWindow", u"Data04", None))
        self.actionDataSub01_01.setText(QCoreApplication.translate("MainWindow", u"DataSub01_01", None))
        self.actionDataSub01_02.setText(QCoreApplication.translate("MainWindow", u"DataSub01_02", None))
        self.actionDataSub01_03.setText(QCoreApplication.translate("MainWindow", u"DataSub01_03", None))
        self.actionDataSub01_04.setText(QCoreApplication.translate("MainWindow", u"DataSub01_04", None))
        self.actionDataSub01_05.setText(QCoreApplication.translate("MainWindow", u"DataSub01_05", None))
        self.actionbdo.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.actionbodong.setText(QCoreApplication.translate("MainWindow", u"\u6ce2\u52a8\u500d\u7387", None))
        self.actionma.setText(QCoreApplication.translate("MainWindow", u"ma", None))
        self.actionregression.setText(QCoreApplication.translate("MainWindow", u"regression", None))
        self.actiontimeseq.setText(QCoreApplication.translate("MainWindow", u"timeseq", None))
        self.actiongarch.setText(QCoreApplication.translate("MainWindow", u"garch", None))
        self.actionpca.setText(QCoreApplication.translate("MainWindow", u"pca", None))
        self.actionbaiys.setText(QCoreApplication.translate("MainWindow", u"baiys", None))
        self.actionfft.setText(QCoreApplication.translate("MainWindow", u"fft", None))
        self.actionarima.setText(QCoreApplication.translate("MainWindow", u"arima", None))
        self.GroupBox01_DataSource.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6570\u636e\u6765\u6e90\uff1a", None))
        self.lab_Specify_API_list_Name.setText(QCoreApplication.translate("MainWindow", u"TuShare\u63a5\u53e3\u5217\u8868", None))
        self.lab_Specify_API_log_Name.setText(QCoreApplication.translate("MainWindow", u"TuShareAPI\u521d\u59cb\u5316\u65e5\u5fd7", None))
        self.lab_Specify_Initial_Path.setText(QCoreApplication.translate("MainWindow", u"TuShare\u521d\u59cb\u5316\u8def\u5f84", None))
        self.pushBttn_API_InitialPath.setText(QCoreApplication.translate("MainWindow", u"\u6307\u5b9aTuShare\u521d\u59cb\u5316\u8def\u5f84", None))
        self.radioBttn04_Other.setText(QCoreApplication.translate("MainWindow", u"Other", None))
        self.radioBttn03_Choice.setText(QCoreApplication.translate("MainWindow", u"Choice", None))
        self.radioBttn02_AST.setText(QCoreApplication.translate("MainWindow", u"AST", None))
        self.radioBttn01_TuShare.setText(QCoreApplication.translate("MainWindow", u"TuShare", None))
        self.pushBttn_API_GeneratList.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6210API\u63a5\u53e3\u6e05\u5355+log \u7ec3\u4e60", None))
        self.lab_Terminal.setText(QCoreApplication.translate("MainWindow", u"\u7ec8\u7aef\u7a97\u53e3", None))
        self.GroupBox02_DataStorage.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6570\u636e\u5b58\u50a8\uff1a", None))
        self.radioBttn01_SSMS_SQL.setText(QCoreApplication.translate("MainWindow", u"Microsoft SQL", None))
        self.radioBttn02_mySQL.setText(QCoreApplication.translate("MainWindow", u"mySQL", None))
        self.radioBttn03_OtherDB.setText(QCoreApplication.translate("MainWindow", u"Other DB", None))
        self.tabWidgetTab01_DB_Select.setTabText(self.tabWidgetTab01_DB_Select.indexOf(self.tab01_MS_SQL), QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e Microsoft SQL", None))
        self.tabWidgetTab01_DB_Select.setTabText(self.tabWidgetTab01_DB_Select.indexOf(self.tab02_mySQL), QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e mySQL", None))
        self.tabWidgetTab01_DB_Select.setTabText(self.tabWidgetTab01_DB_Select.indexOf(self.tab03_OtherDB), QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e Other DB", None))
        self.GroupBox03_DataInitilization.setTitle(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u521d\u59cb\u5316\u8bbe\u7f6e", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab01_DataSetting), QCoreApplication.translate("MainWindow", u"Tab01_\u6570\u636e\u8bbe\u7f6e", None))
#if QT_CONFIG(tooltip)
        self.tabWidget_mainWindow.setTabToolTip(self.tabWidget_mainWindow.indexOf(self.tab01_DataSetting), QCoreApplication.translate("MainWindow", u"\u6570\u636e\u5e93\u8fde\u63a5\u3001\u6570\u636e\u4e0b\u8f7d\u8bbe\u7f6e", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab02_DataDownLoad), QCoreApplication.translate("MainWindow", u"Tab02_\u6570\u636e\u4e0b\u8f7d", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"T301_\u6ce2\u52a8\u500d\u7387", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"T302_\u5747\u503c\u65b9\u5dee", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"T303_\u56de\u5f52", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"T304_\u65f6\u95f4\u5e8f\u5217", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"T305_GARCH\u7c7b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"T306_PCA\u4e3b\u6210\u5206", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"T307_\u8d1d\u53f6\u65af", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"T308_FFT\u9891\u8c31", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"T309_ARIMA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"T310_", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"T311_", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"T312_", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab03_AnalysisSetting), QCoreApplication.translate("MainWindow", u"Tab03_\u5206\u6790\u8bbe\u7f6e", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab04_AnalysisOutput), QCoreApplication.translate("MainWindow", u"Tab04_\u5206\u6790\u7ed3\u679c", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab05_BackTesting), QCoreApplication.translate("MainWindow", u"Tab05_\u56de\u6d4b\u548c\u6267\u884c", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab06_EffectRank), QCoreApplication.translate("MainWindow", u"Tab06_\u6548\u679c\u8bc4\u4ef7", None))
#if QT_CONFIG(tooltip)
        self.tabWidget_mainWindow.setTabToolTip(self.tabWidget_mainWindow.indexOf(self.tab06_EffectRank), QCoreApplication.translate("MainWindow", u"\u5bf9\u6570\u636e\u3001\u89c4\u5219\u3001\u56de\u6d4b\u3001\u5b9e\u76d8\u6548\u679c\u8fdb\u884c\u8bc4\u7ea7", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab07_VersionControl), QCoreApplication.translate("MainWindow", u"Tab07_\u7248\u672c\u63a7\u5236", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab08_SystemMaintenance), QCoreApplication.translate("MainWindow", u"Tab08_\u7cfb\u7edf\u7ef4\u62a4", None))
        self.tabWidget_mainWindow.setTabText(self.tabWidget_mainWindow.indexOf(self.tab09_DevelopDocument), QCoreApplication.translate("MainWindow", u"Tab09_\u5f00\u53d1\u6587\u6863", None))
        self.menu01_File.setTitle(QCoreApplication.translate("MainWindow", u"1_\u6570\u636e\u8bbe\u7f6e", None))
        self.menu02_Data.setTitle(QCoreApplication.translate("MainWindow", u"2_\u6570\u636e\u4e0b\u8f7d", None))
        self.menu03_AnalysisSetting.setTitle(QCoreApplication.translate("MainWindow", u"3_\u5206\u6790\u8bbe\u7f6e", None))
        self.menu04_AnalysisResult.setTitle(QCoreApplication.translate("MainWindow", u"4_\u5206\u6790\u7ed3\u679c", None))
        self.menu05_BackTesting.setTitle(QCoreApplication.translate("MainWindow", u"5_\u56de\u6d4b\u548c\u6267\u884c", None))
        self.menu06_EffectRank.setTitle(QCoreApplication.translate("MainWindow", u"6_\u6548\u679c\u8bc4\u4ef7", None))
        self.menu07_VersionControl.setTitle(QCoreApplication.translate("MainWindow", u"7_\u7248\u672c\u63a7\u5236", None))
        self.menu08_SystemMaintenance.setTitle(QCoreApplication.translate("MainWindow", u"8_\u7cfb\u7edf\u7ef4\u62a4", None))
        self.menu09_DevelopmentDocument.setTitle(QCoreApplication.translate("MainWindow", u"9_\u5f00\u53d1\u6587\u6863", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

